### ISSUE TITLE
Sanity-checking Checklist

### ISSUE THREAD

**Issue by padthaitofuhot** [EMCECS/ECS-CommunityEdition#104]
- [x] Make sure /data directory is empty
- [x] Make sure block devices are unpartitioned
- [x] Make sure ethernet adapter is setup
- [x] Make sure DNS is setup forward and backward
- [x] Make sure NTP skew is not more than 5s between nodes in a VDC
